#! /bin/bash
#This file is part of LinuxRCD.
#
#    LinuxRCD is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    LinuxRCD is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with LinuxRCD.  If not, see <http://www.gnu.org/licenses/>.
#


#This script is called up by the script that promts the user for what system to mount. It is carried into the users target system with a binded mount in a non standard location, and then chrooted to do some work to prep the target system for recovery, and then calls up the apps.





#set the display variable so that X apps start a GUI
export DISPLAY=localhost:1

#many apps need the home variable set.
export HOME=/root

export PATH=$PATH:"/usr/LinuxRCD-Recovery-Tools-And-Data"
##CALL THE STARTUP APPS

#call up the windowing manager
#openbox

#set the Pangorc file
export PANGO_RC_FILE=/usr/LinuxRCD-Recovery-Tools-And-Data/pango/pangorc

#call up xsettings manager, GTK apps like this.
lxsession &

#grab the previous PID
pid=$!
#use GDB to unset the PANGO_RC_FILE variable on the process and its current child processess so it isn't used anymore
echo "unset_pango:$pid" > /usr/LinuxRCD-Recovery-Tools-And-Data/chroot_helper_command_socket 

#call up the file browser opened to the folder containg the launchers 
pcmanfm --no-desktop /usr/LinuxRCD-Recovery-Tools-And-Data/launchers &

#grab the previous PID
pid=$!
#use GDB to unset the PANGO_RC_FILE variable on the process and its current child processess so it isn't used anymore
echo "unset_pango:$pid" > /usr/LinuxRCD-Recovery-Tools-And-Data/chroot_helper_command_socket

#call up the panel
fspanel &

#grab the previous PID
pid=$!
#use GDB to unset the PANGO_RC_FILE variable on the process and its current child processess so it isn't used anymore
echo "unset_pango:$pid" > /usr/LinuxRCD-Recovery-Tools-And-Data/chroot_helper_command_socket

#unset the pangorc file. all child processess will use the  system default
unset PANGO_RC_FILE


