#! /bin/bash
#This file is part of LinuxRCD.
#
#    LinuxRCD is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    LinuxRCD is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with LinuxRCD.  If not, see <http://www.gnu.org/licenses/>.
#




#try to mount fstab in case user has seperate partions, such as home. (it may not work because the users fstab may be broken) DOING THIS OUTSIDE NOW.
#mount -a

#mount the procfs
mount -t proc none /proc



#mount sysfs
mount -t sysfs none /sys

#mount /dev/pts
mount -t devpts none /dev/pts

#mount /dev/shm
mount -t tmpfs none /dev/shm

#provide a link so that the filesystems such as flash drives can be imported into the recovery system
ln -s /proc/1/root/media /FileSystems

#set the display variable so that X apps start a GUI
export DISPLAY=localhost:1

#many apps need the home variable set.
export HOME=/root

export PATH=$PATH:/usr/recoverystuff
##CALL THE STARTUP APPS

#call up the windowing manager
#openbox

#call up the file browser opened to the folder containg the launchers TODO a more user friendly file browser could be found...
emelfm2 -i  --one=/usr/recoverystuff/launchers --two=/usr/recoverystuff/launchers &

#call up the panel
fspanel &



