#! /bin/bash
#This file was last modified 08/04/002010 (Gregorian Calendar) 01:45 UTC
#execute the script that calls the app in a different namespace so that whatever is mounted and unmounted does not effect the whole system
/opt/recoverystuff/bin/unshare -m /opt/recoverystuff/recoverystuff/launch_text_editor.sh > /dev/null 2>&1

