#! /bin/bash 
#    Copyright (c) 2009, 2010, 2011, nerdopolis (or n3rdopolis) <bluescreen_avenger@version.net>
#
#    This file is part of LinuxRCD.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


#this script will take one argument, that is the package name to be built
buildpackage="$1"

#create a directory for building the selected package in the current dircetory. 
mkdir $buildpackage
#switch into the new directory
cd $buildpackage
#get the source for the package
su  builder -c apt-get source $buildpackage
#get all the build requirements for the package
echo Y | apt-get build-dep $buildpackage

