#! /bin/bash
#    Copyright (c) 2009, 2010, 2011, nerdopolis (or n3rdopolis) <bluescreen_avenger@version.net>
#
#    This file is part of LinuxRCD.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
TARFILE="$1"
echo "editing tar file $TARFILE"
buildpackage="$2"
TARFILE=$(readlink -f $TARFILE)
#get the file name
tarname=$(echo $TARFILE | rev | awk -F / '{print $1}' | rev)
extension=$(echo $tarname | rev | awk -F . '{print $1}' | rev) 
#create a folder for modifying the tar file, as debian quilt wants it
mkdir "/tmp/$tarname"
#grab the current directory
startpath=$PWD
#change into the folder
cd "/tmp/$tarname"
#extract the tar file
tar -axvf "$TARFILE"

echo "Patching the files in $TARFILE to not use usr"
#modify the source tree
sourceedit "/tmp/$tarname" $buildpackage
#recreate the tar with the modified source
tar -acvf  "$TARFILE" .
#change back
cd $startpath
#delete the folder for the tar
rm -rf "/tmp/$tarname"