#! /bin/bash
#This file is part of LinuxRCD.
#
#    LinuxRCD is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    LinuxRCD is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with LinuxRCD.  If not, see <http://www.gnu.org/licenses/>.
#

#@@@TRANSLATABLE_FILE@@@
#@@@TRANSLATABLE_FILENAME@@@~~~~~~~~~~~should just say "terminal"~~~~~~~~~~~

export PATH=$PATH:"/usr/LinuxRCD-Recovery-Tools-And-Data"

#set the Pangorc file
export PANGO_RC_FILE=/usr/LinuxRCD-Recovery-Tools-And-Data/pango/pangorc


#call up the terminal
cd /
lxterminal  --working-directory=/ -e 'bash --init-file /etc/bash_completion' &

#grab the previous PID
pid=$!
#use GDB to unset the PANGO_RC_FILE variable on the process and its current child processess so it isn't used anymore
echo "unset_pango:$pid" > /usr/LinuxRCD-Recovery-Tools-And-Data/chroot_helper_command_socket

#unset the pangorc file. all child processess will use the  system default
unset PANGO_RC_FILE