#! /bin/bash

##Run the method to safely unmount the target system in case if the user leaves it open

kdialog --yesno "Are you sure you want to shutdown?"

if (($?==0))
then
#kill all X apps by destroying the display. Many apps perform a safe exit routine when the X server dies
killall Xephyr

#gently kill any other processess
fuser -15 -k /media/RecoveryMount

#change the hostname of the live cd back to the default
hostname -F /etc/hostname

# TODO this might need to wait, but the command might do that for us

#forcibly kill the processess
fuser -k /media/RecoveryMount

#unlink the symlink created
unlink /media/RecoveryMount/FileSystems

#unmount recovery systems /sys
umount -lf /media/RecoveryMount/sys

#unmount recovery systems /proc
umount -lf /media/RecoveryMount/proc

#unmount recovery systems /dev/pts
umount -lf /media/RecoveryMount/dev/pts

#unmount recovery systems /dev
umount -lf /media/RecoveryMount/dev

#unmount the dbus folder
umount /media/RecoveryMount/var/run/dbus

#unmount the X11 authroization folder
umount /media/RecoveryMount/tmp/.X11-unix

#unmount the /usr folder
umount /media/RecoveryMount/opt/recoverystuff

#unmount all fstab partitions
chroot /media/RecoveryMount umount -a

#unmount the recovered systems fs
umount -lf /media/RecoveryMount

shutdown -P now
fi
