#! /bin/sh

#allow the recovery imported apps to see the ldconfigs
#mount --bind /etc /usr/recoverystuff/etc

#allow the recovery imported apps to see the base executables
#mount --bind /bin /usr/recoverystuff/bin

#allow the recovery imported apps to see the base /lib folders
#mount --bind /lib   /usr/recoverystuff/lib
#mount --bind /lib32 /usr/recoverystuff/lib32
#mount --bind /lib64 /usr/recoverystuff/lib64


/usr/bin/recoverylauncher &
